import { NextRequest, NextResponse } from 'next/server'
import { createSupabaseServer } from '@/lib/supabase-server'
import { sendBookingConfirmation } from '@/lib/whatsapp'
import { sendBookingEmail } from '@/lib/email'

export async function GET(req: NextRequest) {
  const supabase = createSupabaseServer()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const status = searchParams.get('status')
  const date = searchParams.get('date')

  let query = supabase.from('bookings')
    .select('*, court:courts(name, display_name, wpc_id), center:centers(name, city)')
    .eq('profile_id', user.id)
    .order('date', { ascending: false })
    .order('start_time')

  if (status) query = query.eq('status', status)
  if (date) query = query.eq('date', date)

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json(data)
}

export async function POST(req: NextRequest) {
  const supabase = createSupabaseServer()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json()
  const { court_id, center_id, date, start_time, end_time, duration_min, pricing_rule_id, is_recurring, recurring_weeks } = body

  if (!court_id || !center_id || !date || !start_time || !end_time) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  // Check court availability
  const { data: existing } = await supabase.from('bookings')
    .select('id')
    .eq('court_id', court_id)
    .eq('date', date)
    .in('status', ['confirmed', 'pending'])
    .lt('start_time', end_time)
    .gt('end_time', start_time)
    .limit(1)

  if (existing && existing.length > 0) {
    return NextResponse.json({ error: 'Court not available at this time' }, { status: 409 })
  }

  // Fetch pricing
  let basePrice = 0
  let discountPct = 0
  if (pricing_rule_id) {
    const { data: rule } = await supabase.from('pricing_rules')
      .select('price_per_slot, requires_membership')
      .eq('id', pricing_rule_id)
      .single()
    if (rule) basePrice = rule.price_per_slot
  }

  // Check membership discount
  const { data: membership } = await supabase.from('memberships')
    .select('*, plan:membership_plans(discount_pct)')
    .eq('profile_id', user.id)
    .eq('center_id', center_id)
    .eq('status', 'active')
    .limit(1)
    .single()

  if (membership?.plan?.discount_pct) {
    discountPct = membership.plan.discount_pct
  }

  const discountAmount = basePrice * (discountPct / 100)
  const totalPrice = basePrice - discountAmount

  // Build booking dates
  const weeks = is_recurring && recurring_weeks ? recurring_weeks : 1
  const bookingDates: string[] = []
  const startDate = new Date(date + 'T00:00:00')
  for (let i = 0; i < weeks; i++) {
    const d = new Date(startDate.getTime() + i * 7 * 86400000)
    bookingDates.push(d.toISOString().split('T')[0])
  }

  // Create recurring series if recurring
  let recurringId: string | null = null
  if (is_recurring && weeks > 1) {
    const dayOfWeek = startDate.getDay()
    const { data: series } = await supabase.from('recurring_series')
      .insert({
        user_id: user.id,
        court_id,
        start_time,
        end_time,
        day_of_week: dayOfWeek,
        weeks,
        price_per_session: totalPrice,
        status: 'active',
      })
      .select('id')
      .single()
    recurringId = series?.id || null
  }

  // Insert all bookings (PIN generated by DB trigger for each)
  const bookingRows = bookingDates.map(d => ({
    court_id,
    center_id,
    profile_id: user.id,
    date: d,
    start_time,
    end_time,
    duration_min: duration_min || 90,
    status: 'confirmed' as const,
    payment_status: 'pending' as const,
    payment_mode: 'on_site' as const,
    base_price: basePrice,
    discount_pct: discountPct,
    discount_amount: discountAmount,
    total_price: totalPrice,
    is_recurring: weeks > 1,
    recurring_id: recurringId,
    recurring_weeks: weeks > 1 ? weeks : null,
  }))

  const { data: bookings, error } = await supabase.from('bookings')
    .insert(bookingRows)
    .select('*, court:courts(name, display_name), center:centers(name, city)')

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  const booking = bookings[0]
  const courtName = booking.court?.display_name || booking.court?.name || ''
  const centerName = booking.center?.name || ''
  const pin = booking.pin_code || ''

  // Insert in-app notification
  const notifMessage = weeks > 1
    ? `${courtName} | ${weeks} sesiones | ${booking.start_time?.slice(0,5)}-${booking.end_time?.slice(0,5)}`
    : `Court: ${courtName} | PIN: ${pin} | ${booking.start_time?.slice(0,5)}-${booking.end_time?.slice(0,5)}`
  await supabase.from('notifications').insert({
    user_id: user.id,
    title: weeks > 1 ? 'Serie recurrente creada' : 'Reserva confirmada',
    message: notifMessage,
    type: 'booking_confirmed',
    booking_id: booking.id,
  })

  // Send WhatsApp confirmation
  const { data: profile } = await supabase.from('profiles')
    .select('phone, first_name')
    .eq('id', user.id)
    .single()

  console.log('=== BOOKING CREATED ===', booking.id, weeks > 1 ? `(${weeks} weeks)` : '')
  console.log('=== PIN (from trigger) ===', pin)

  if (profile?.phone && process.env.TWILIO_ACCOUNT_SID) {
    try {
      const result = await sendBookingConfirmation({
        phone: profile.phone,
        pin,
        courtName,
        date: booking.date,
        startTime: booking.start_time.slice(0, 5),
        endTime: booking.end_time.slice(0, 5),
        centerName,
        totalPrice: weeks > 1
          ? `${(totalPrice * weeks).toFixed(2)} EUR (${weeks} sesiones)`
          : `${totalPrice.toFixed(2)} EUR`,
      })
      console.log('=== WHATSAPP SENT ===', result)
    } catch (err) {
      console.error('=== WHATSAPP ERROR ===', err)
    }
  }

  // Send email confirmation
  if (user.email && process.env.RESEND_API_KEY) {
    try {
      await sendBookingEmail({
        to: user.email,
        pin,
        courtName,
        date: booking.date,
        startTime: booking.start_time.slice(0, 5),
        endTime: booking.end_time.slice(0, 5),
        centerName,
        totalPrice: totalPrice * weeks,
      })
      console.log('=== EMAIL SENT ===', user.email)
    } catch (err) {
      console.error('=== EMAIL ERROR ===', err)
    }
  }

  // Send OneSignal push notification
  const pushContent = weeks > 1
    ? `${courtName} | ${weeks} sesiones | ${booking.start_time?.slice(0,5)}`
    : `Court: ${courtName} | PIN: ${pin} | ${booking.start_time?.slice(0,5)}`
  await fetch('https://onesignal.com/api/v1/notifications', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.ONESIGNAL_REST_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      app_id: '435c277a-d4cc-489b-86a9-92c95c8e6353',
      included_segments: ['All'],
      headings: {
        en: weeks > 1 ? 'CERTICOURT - Recurring booking created' : 'CERTICOURT - Booking confirmed',
        es: weeks > 1 ? 'CERTICOURT - Serie recurrente creada' : 'CERTICOURT - Reserva confirmada',
      },
      contents: { en: pushContent, es: pushContent },
      url: 'https://certicourt-booking.vercel.app/agenda',
    }),
  }).catch(err => console.error('OneSignal error:', err))

  return NextResponse.json(booking, { status: 201 })
}
